### ISSUE TITLE
SharedTokenCacheCredential fails in WSL when logged into az CLI

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12939]
Seems I can't use the SharedTokenCacheCredential on WSL when logged into the az CLI or PowerShell Core.

Environment
* Ubuntu 18.04 (latest updates installed) in WSL2
* .NET core 3.1.301
* Windows 10 2004
* `az version`:
```json
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

Stack trace:
```
Unhandled exception. Azure.Identity.AuthenticationFailedException: DefaultAzureCredential authentication failed.
 ---> Azure.Identity.AuthenticationFailedException: SharedTokenCacheCredential authentication failed.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'attributeValue1')
   at Microsoft.Identity.Client.Extensions.Msal.CacheAccessorLinux..ctor(String cacheFilePath, String keyringCollection, String keyringSchemaName, String keyringSecretLabel, String attributeKey1, String attributeValue1, String attributeKey2, String attributeValue2, TraceSourceLogger logger)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.Create(StorageCreationProperties creationProperties, TraceSource logger)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper..ctor(StorageCreationProperties storageCreationProperties, TraceSource logger, HashSet`1 knownAccountIds, FileSystemWatcher cacheWatcher)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationProperties storageCreationProperties, TraceSource logger)
   at Azure.Identity.MsalPublicClient.InitializeAsync()
   at Azure.Identity.MsalPublicClient.EnsureInitializedAsync(Boolean async)
   at Azure.Identity.MsalPublicClient.GetAccountsAsync()
   at Azure.Identity.SharedTokenCacheCredential.GetAccountAsync()
   at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.SharedTokenCacheCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.GetPage[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, String operationName, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.Secrets.SecretClient.<>c__DisplayClass13_0.<GetPropertiesOfSecrets>b__0(String nextLink)
   at Azure.Core.PageResponseEnumerator.<>c__DisplayClass0_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
   at Azure.Core.PageResponseEnumerator.FuncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Pageable`1.GetEnumerator()+MoveNext()
   at test.Program.Main(String[] args) in /home/heaths/test/Program.cs:line 12
```

Sample code:
```csharp
﻿using System;
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new SecretClient(new Uri("https://heathskv.vault.azure.net"), new DefaultAzureCredential());
            foreach (SecretProperties secret in client.GetPropertiesOfSecrets())
            {
                Console.WriteLine(secret.Id);
            }
        }
    }
}
```

Using packages:

```xml
    <PackageReference Include="azure.identity" Version="1.2.0-preview.4" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.3" />
```

**Comment by sig9** [comment]
I am getting the same error on an Ubuntu 18.04 vm running in Azure.  I have azure.identity 1.2.0-preview.4.

**Comment by joshfree** [comment]
Moving to August milestone

**Comment by AlexanderSher** [comment]
LinuxKeyRingAccessor implementation: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/src/Microsoft.Identity.Client.Extensions.Msal/Accessors/LinuxKeyRingAccessor.cs

**Comment by ohadschn** [comment]
We're hitting a similar issue in our container (CDPx ubuntu-1804) executions:
```
at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.SharedTokenCacheCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, Boolean async, CancellationToken cancellationToken)
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async)
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
at [REDACTED - our product code]
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
at Microsoft.Identity.Client.Extensions.Msal.LinuxKeyringAccessor..ctor(String cacheFilePath, String keyringCollection, String keyringSchemaName, String keyringSecretLabel, String attributeKey1, String attributeValue1, String attributeKey2, String attributeValue2, TraceSourceLogger logger)
at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.Create(StorageCreationProperties creationProperties, TraceSource logger)
at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper..ctor(StorageCreationProperties storageCreationProperties, TraceSource logger, HashSet`1 knownAccountIds, FileSystemWatcher cacheWatcher)
at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationPrope
```
It looks like a similar issue was hit in the past for a different provider: https://github.com/Azure/azure-sdk-for-net/issues/12749. Would it be possible to implement a more generic solution, where provider failures are reported more clearly (e.g. "provider not available" / "all default providers failed").

**Comment by AlexanderSher** [comment]
Issue has been caused by the `MsalCacheStorage` and has been [fixed](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/732004a10bdd24fc4125d0fe8f5d7e32d3ec1069/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheStorage.cs#L76) in `microsoft.identity.client.extensions.msal` version `2.12.0`. `Azure.Identity` has updated its reference in [`1.2.0-preview.6`](https://www.nuget.org/packages/Azure.Identity/1.2.0-preview.6).

@ohadschn , what version of Azure.Identity do you have?

**Comment by ohadschn** [comment]
We're using `Azure.Identity 1.2.3` and `Azure.Core 1.5.0`

**Comment by apavlunenko** [comment]
Issue is reproducible every time using 1.2.3
Downgrading to 1.2.2 resolves the problem

**Comment by schaabs** [comment]
This is fixed by https://github.com/Azure/azure-sdk-for-net/pull/15944 and will be released in the 1.3.0 release of Azure.Identity

**Comment by lextas** [comment]
I am still experiencing this problem on version 1.3.0. It happens when I run the code in the `program.cs` startup of a `dotnet core 3.1` API. The configure services contains the same code (accessing the `Azure KeyVault`) but this doesn't throw an error.

This is the line that throws there error in the startup
```
var keyVault = new SecretClient(new Uri(context.Configuration.GetValue<string>("KeyVault")), new DefaultAzureCredential());
```

**Comment by lextas** [comment]
I am still experiencing this bug but only when I try to access the key vault from `Program.cs`. I am trying to get a key from the vault to register a Serilog sink. Since `Startup` is the only place where I can register the logger it needs to be done there. 

The following line works locally (Windows) but not on Azure (running in a Linux docker container)

`var keyVault = new SecretClient(new Uri(context.Configuration.GetValue<string>("KeyVault")), new DefaultAzureCredential());`

The same line is used in the `UseServices` block and there it runs fine. So it seems like it has to do with the fact that the Azure identity is somehow not present when starting up the container?

It's a dotnet core 3.1 solution with Azure.Identity v1.3.0.

**Comment by heaths** [comment]
@lextas I recommend opening a new issue since this seems unrelated. This bug was a problem with azure CLI credentials running in a WSL2 container. If your managed identity isn't detected from within a container that may be a different issue entirely.

**Comment by Hopp3r** [comment]
@lextas did you open an issue for this or figure it out? I'm also trying to figure out how to configure my SecretClient to work with a docker container.

**Comment by lextas** [comment]
No I didn't. It worked with the DefaultCredentials but only if my app was already started. If it was in the startup phase (kestrel `program.cs`) then it would throw an error. I don't know if it had anything to do with the docker itself.

**Comment by goncalvesj** [comment]
Hi guys,

I'm still running into this issue when developing locally in WSL2 (Ubuntu 20.04).

The current setup is:
NET 5 web app
Azure.Identity="1.3.0"
VS Code 1.52.1

If I use:
`var blobServiceClient = new BlobServiceClient(accountUri, new DefaultAzureCredential());`

I get:
`SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details
      Azure.Identity.AuthenticationFailedException: SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details
       ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Inspect inner exception for details
       ---> System.DllNotFoundException: Unable to load shared library 'libsecret-1.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsecret-1.so.0: cannot open shared object file: No such file or directory`

My workaround for now is to use `new AzureCliCredential()` and everything runs locally.

It's worth point out that this doesn't happen when the app is deployed to Azure in a container, uses Managed Identity and ` new DefaultAzureCredential()` .
