### ISSUE TITLE
[FEATURE REQ] DefaultAzureCredential for local docker testing

### ISSUE THREAD

**Issue by et1975** [Azure/azure-sdk-for-net#19167]
**Azure.Identity**
Testing code that uses `DefaultAzureCredential` in a container locally seems to require a lot of effort, unless one is willing to supply username/password into the environment.
Creating a service principal and supplying the clientID + Secret is not much better, but also requires a whole lot of additional effort - like setting up the SP, granting the permissions that the developer account already has, etc.

There should be a way to use VS/VSCode/CLI tokens simply by mounting `~/.azure` into `/root/.azure` of the container, unfortunately this does not work today. #12749 mentions installation of the CLI as a working solution, but I just tried this on Alpine and 
a) it's a hassle - installing all that stuff on Alpine is error-prone experience and takes a long time (on each build!)
b) it doesn't work, as I still get the exception

>  SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details
       ---> Azure.Identity.AuthenticationFailedException: SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details
       ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Inspect inner exception for details
       ---> System.DllNotFoundException: Unable to load shared library 'libsecret-1.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibsecret-1.so.0: No such file or directory
         at Microsoft.Identity.Client.Extensions.Msal.Libsecret.secret_schema_new(String name, Int32 flags, String attribute1, Int32 attribute1Type, String attribute2, Int32 attribute2Type, IntPtr end)
         at Microsoft.Identity.Client.Extensions.Msal.LinuxKeyringAccessor.GetLibsecretSchema()
         at Microsoft.Identity.Client.Extensions.Msal.LinuxKeyringAccessor.Write(Byte[] data)
         at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.VerifyPersistence()
         --- End of inner exception stack trace ---
         at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.VerifyPersistence()
         at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.VerifyPersistence()
         at Azure.Identity.MsalClientBase`1.GetClientAsync(Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.MsalClientBase`1.GetClientAsync(Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.MsalPublicClient.GetAccountsAsync(Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.SharedTokenCacheCredential.GetAccountAsync(Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)

**Comment by et1975** [comment]
I figured a workaround just now:
- have a Dockerfile just for running stuff locally (not a great start, but easier than the alternatives)
- that uses mcr.microsoft.com/azure-cli as the base image and 
- in docker-compose has:
```
volumes:
 - ~/.azure:/root/.azure 
``` 
And in the code sets up the auth chain:

`ChainedTokenCredential(ManagedIdentityCredential() or EnvironmentCredential(), AzureCliCredential())`

This works, but would be great if we didn't need az cli in the first place.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jongio** [comment]
See here for how I do it, which is the same as you, but checkout the CLI install script in my dev container, it's a one liner. 

`RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash`

VIDEO: https://youtu.be/oDNGs7B2g1A
CODE: https://github.com/jongio/azureclicredentialcontainer

The only thing better than this would be local ManagedIdentity, but that isn't available right now.  We have discussed it, but it opens issues that need to be fleshed out.

**Comment by nhart12** [comment]
Agreed, to be able use/mount IDE azure credentials when local testing would be awesome. Azure CLI bloats images by almost a gig

**Comment by jdthorpe** [comment]
> See here for how I do it, which is the same as you, but checkout the CLI install script in my dev container, it's a one liner.
> 
> `RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash`
> 
> VIDEO: https://youtu.be/oDNGs7B2g1A CODE: https://github.com/jongio/azureclicredentialcontainer
> 
> The only thing better than this would be local ManagedIdentity, but that isn't available right now. We have discussed it, but it opens issues that need to be fleshed out.

@jongio, This worked for me up until I upgraded my Azure CLI to 2.33.  Now it seems the windows host machine encrypts the tokens in a `.bin` file, but the linux azure CLI inside the container expects the unencrypted `.json` file, so I get a message inside the container stating `Please run 'az login' from a command prompt to authenticate before using this credential.` inside the container, but the same code running on the windows host fetches an access token without issue.

**Comment by philipwolfe** [comment]
@et1975 @jdthorpe @jongio @christothes  I am running into this too.  Here is what I came up with.  We too need ways for a container running on a QA engineer machine to authenticate to Azure without checking credentials into SCC in a YAML file.  Would love some feedback.  My goal is to take the access token from the engineer and use it for this session...doesn't need to be long term like the EnvironmentCredential.
https://github.com/philipwolfe/azure-sdk-for-net/commit/5dff08d75bdb41a1bef4618d2478adbfb6f02338
based on ideas from: https://stackoverflow.com/a/61498506/13122820

**Comment by jdthorpe** [comment]
@philipwolfe [this solution](https://github.com/jongio/azureclicredentialcontainer/issues/2#issue-1128909238) may work for you for now.  It essentially requires installing a previous version of the Azure CLI onto both the host machine and in the container, logging into Azure (`az login`) on the host machine, mapping the `~/.azrue` directory into the container.

**Comment by goenning** [comment]
We're also using the CLI solution, but the az cli on developer machines is auto updating to the 2.33 version, so that means every day developers have to downgrade to 2.29.

Based on az cli docs, it's not meant to auto-upgrade by default, but apparently it is...

```
By default, auto-upgrade for Azure CLI is disabled. If you would like to keep up with the latest version, you can enable auto-upgrade through [configuration](https://docs.microsoft.com/en-us/cli/azure/config).
```

**Comment by tpanum** [comment]
Surreal to read that no progress has been made on such a fundamental problem for over a year. Much like the Python counter part ([azure-identities](https://github.com/Azure/azure-sdk-for-python)), this package simply seems to be poorly designed, as it relies on some unversioned binary to function. Thus this binary dependency has to be baked in to the container images, despite serving no use in production.

The least destructive hack I have come up with is simply to retrieve secrets (e.g. access token) from my host machine (using Azure CLI) and pass it into my docker container using environment variables, and overrule the azure-identity clients, like so:
`docker run -e TOKEN=$(az account get-access-token --resource <resource-id> | jq -r .accessToken) my/fantastic-image`.

**Comment by paupal1** [comment]
Also running into this issue... Is there a recommended workaround other than downgrading AzCli version?

**Comment by dmitriyse** [comment]
Was forced to write a tool that proxies the local tokens for local user (obtained from the DefaultAzureCredential) to the container through the same protocol as MSI are delivered to the ARC enabled servers.
https://github.com/ClrCoder/ClrPro.AzureFX/releases/tag/v0.1.0

This tool should be executed from a developer account on port 40342
```PowerShell
$env:ASPNETCORE_URLS="http://+:40342"
.\ClrPro.Azure.LocalCredentialBridge.exe
```

Then container should have the next env, volumes:
```
docker ....
      -e IDENTITY_ENDPOINT=http://host.docker.internal:40342/metadata/identity/oauth2/token
      -e IMDS_ENDPOINT=http://host.docker.internal:40342 
      -v %USERPROFILE%/.LocalCredentialBridgeTokens:/var/opt/azcmagent/tokens:ro
      ...
 ```
 
 And the DefaultAzureCredential will work inside the container.

**Comment by dmitriyse** [comment]
Ideally such functionality should be inside Visual Studio out of the box.
1) Docker containers development is a first-class feature of the Visual Studio
2) Azure secret-less resource access is a first-class feature of the Azure SDK
3) Azure connectivity from Visual-Studio again is a first class feature

Why developers should do the IDE enhancement job for the first class features to make them works together ?

Lack of support of zero secrets connectivity is appearing here and there. For example here there was also a problem https://github.com/dotnet/efcore/issues/26491

Please increase the priority of this feature request.
It's spanning a year already.

**Comment by esimkowitz** [comment]
Hi @jongio, any updates here? While we would like to get all our developers working in Docker containers to improve compatibility with our production environments, requiring a complicated login process versus just running in VS is too much of a burden.

**Comment by asanjabi** [comment]
@esimkowitz one workaround is to mount a volume that's shared between all containers, you'd have to connect to one and login once, but the rest will be fine after that.  You would need to install the CLI on all the images, so there is that.  Not ideal, but workable [sample](https://github.com/asanjabi/DaprDemo/blob/3a0c9b992b2f248b34509d1b5a9e14a9277553d4/docker-compose.override.yml#L13)

**Comment by esimkowitz** [comment]
Frankly that seems like more work to explain to my devs and write troubleshooting docs for than to just tell them to test their changes separately against our Linux environments.

**Comment by stefanolsenn** [comment]
We fixed it by injecting the environment variables into the containers: in our docker-compose file and using InTune to set the environment variables on all developer pc's.
```  service:
      [...]
        environment:
         - AZURE_TENANT_ID
         - AZURE_CLIENT_ID
         - AZURE_CLIENT_SECRET
      [...]

**Comment by esimkowitz** [comment]
That kind of fix won't work for us. We do not store client credentials on local dev boxes, we need to have RBAC set up to someone's own account for any dev resources. We are able to use DefaultAzureCredential in Visual Studio with no issue, ideally this should pipe automatically into Docker when running locally.

**Comment by dmitriyse** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/19167#issuecomment-1127081646

Please try this approach. Works good enough in our team. 
Visual Studio Credential get passed into containers.

~ 1/2 Year, all good, we forgot about this problem.

**Comment by mykola-yakovliev** [comment]
Just to add another argument to this problem: for someone (like me), who is new to development of cloud solutions using Azure and wants to try things out, it is a little bit frustrating experience to get an exception after you generate the project from a template and just want it **to run with zero-configuration needed**. Of course, it is not really much critical in my case, but from my point of view, people would expect it to work locally out-of-box equally with or without Docker.

**Comment by esimkowitz** [comment]
@jongio @jsquire any updates here on prioritizing this ask? I think this is a very popular scenario given the increasing focus on Dockerizing development and debug environments.

**Comment by jsquire** [comment]
Hi @esimkowitz.   I have no insight; my role for this issue was only initial triage.  Any updates would need to be provided by the assigned engineers, @christothes and @schaabs).

**Comment by dmitriyse** [comment]
Updated the LocalCredentialBridge utility:
https://github.com/ClrCoder/ClrPro.AzureFX/releases/tag/v0.1.1

**Comment by jongio** [comment]
@dmitriyse - Do you have more info on that?

**Comment by jonms90** [comment]
I am running into the same issue for local development with docker containers in Visual Studio 2022 that relies on Azure services. In production/test I use Managed Identities without any issue, but that is not an option locally. The code uses the chained DefaultAzureCredential to support multiple credential providers. To summarize;

- EnvironmentalCredential: This works fine for User accounts, but not when MFA is enabled (which should always be enabled). The other option here is to use a Service Principal and pass in the client credentials using a .env file that is not checked in to source control. This works, but it is a hassle to manage with a lot of management overhead when your development teams starts to grow.
- ManagedIdentityCredential: As mentioned: works great for test/prod, but not available for local development.
- SharedTokenCacheCredential: There is little to no documentation on how this is supposed to work with a container?
- VisualStudioCredential: This is what I would expect to be the default developer experience in 2022, but it does not seem to be integrated with docker container support in VisualStudio. Ideally, logging into VS should be enough to authenticate regardless of running in a container or not. Unfortunately this is not how it works.
- Using Azure CLI. Another option that works with some hacks including mounting azure folders onto the running container, but the largest downside is that we have to include the Azure CLI in our container images. This dramaticly bloats our images and really is not an option considering the amount of images we create.
- InteractiveBrowserCredential does not seem to do anything when running in a container context

Using Visual Studio 2022, Azure and Docker in combination should not be this complicated. This seems like a very basic setup that will hit everyone trying to containerize their cloud-native applications. I must be missing something obvious.

**Comment by jonms90** [comment]
I guess the lesser evil is to use a Service Principal for each user, but that really does not seem to be the correct way of solving this issue.

**Comment by NCarlsonMSFT** [comment]
Update on this: I am a dev on the Container Tools team in VS and we are actively working on solving this issue; but unfortunately, I can't give you an exact timeline for when support will ship. Until then I have two samples to try and make the current experience more bearable: [EnvironmentCredentialExample](https://github.com/NCarlsonMSFT/EnvironmentCredentialExample) and [AzureCliCredentialExample](https://github.com/NCarlsonMSFT/AzureCliCredentialExample). Both use a combination of PowerShell scripts and debugging customizations to make the process of authenticating in development containers as straight forward as possible.

**Comment by Augustukas** [comment]
bump

**Comment by BC89** [comment]
Incredibly frustrating.  MS pushing Dockerized approach in all the VS2002 marketing BS and something as fundamental as this breaks down.

**Comment by BC89** [comment]
Looks like 1.9.0-beta.2 just hit and this still hasn't been addressed.

**Comment by NCarlsonMSFT** [comment]
Update: Using the new [Azure.Identity 1.9.0-beta.2](https://www.nuget.org/packages/Azure.Identity/1.9.0-beta.2) and [Visual Studio 2022 17.6 Preview 1](https://visualstudio.microsoft.com/vs/preview/#download-preview) the `VisualStudioCredential` should now work when using Visual Studio to Launch a .NET Core project in a Windows or Linux container.

**Comment by BC89** [comment]
Can confirm that Nathan is correct and this issue appears to be addressed with that combination out of the box. Thanks!

**Comment by saravanakumarvelayutham** [comment]
I ran into the same problem to allow running docker-compose with mounted volume of az token location to the container from the windows host. Using the beta identity also did not work . 

Since window az cli uses credentials manager to encrypt, it generates the token cache in ".bin" format. While Linux cli generates ".json" token cache. To make the mount work from windows host to docker container , I disabled the encryption when logging into az cli from windows. 

`az config set core.encrypt_token_cache=false`

https://github.com/Azure/azure-cli/issues/21010#issuecomment-1104844455

I hope this helps someone :)  

Still looking for way without disabling encryption

**Comment by karpikpl** [comment]
hey @NCarlsonMSFT is there planned support for VS Code solution that uses `VisualStudioCredential`, where Docker Desktop is not needed?

**Comment by NCarlsonMSFT** [comment]
@karpikpl that would be a good question to ask at: https://github.com/microsoft/vscode-docker.

**Comment by IisAnh** [comment]
> Update: Using the new [Azure.Identity 1.9.0-beta.2](https://www.nuget.org/packages/Azure.Identity/1.9.0-beta.2) and [Visual Studio 2022 17.6 Preview 1](https://visualstudio.microsoft.com/vs/preview/#download-preview) the `VisualStudioCredential` should now work when using Visual Studio to Launch a .NET Core project in a Windows or Linux container.

Hey @NCarlsonMSFT , is there an example of the VisualStudioCredential working with these packages that I could look at just like your other examples?

**Comment by NoamTD** [comment]
@NCarlsonMSFT When trying the setup you described I get this error: `Visual Studio Token provider can't be accessed at /root/.IdentityService/AzureServiceAuth/tokenprovider.json`.
Do I need to do anything special to make it work?

**Comment by karpikpl** [comment]
> @NCarlsonMSFT When trying the setup you described I get this error: `Visual Studio Token provider can't be accessed at /root/.IdentityService/AzureServiceAuth/tokenprovider.json`. Do I need to do anything other than Using [Azure.Identity 1.9.0-beta.2](https://www.nuget.org/packages/Azure.Identity/1.9.0-beta.2) and [Visual Studio 2022 17.6 Preview 1](https://visualstudio.microsoft.com/vs/preview/#download-preview) to make it work?

I got the same thing when I was trying to run it in this setup.

**Comment by NCarlsonMSFT** [comment]
@IisAnh There is now: https://github.com/NCarlsonMSFT/VisualStudioCredentialExample

**Comment by NCarlsonMSFT** [comment]
@NoamTD, @karpikpl Probably you need to update [Microsoft.VisualStudio.Azure.Containers.Tools.Targets](https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets) to 1.18.1 (my bad didn't mention it earlier).

**Comment by flashQarl** [comment]
> @IisAnh There is now: https://github.com/NCarlsonMSFT/VisualStudioCredentialExample

Hi! This example does not work for me. I get this error:

```
DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/workloadidentitycredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
- Azure Developer CLI could not be found.
- Visual Studio Token provider can't be accessed at /root/.IdentityService/AzureServiceAuth/tokenprovider.json
- Azure CLI not installed
- PowerShell is not installed.
```

**Comment by NCarlsonMSFT** [comment]
@flashQarl Looking through Azure.Identity, that seems to happen when there is a problem reading the configuration file. Could you try launching a second time after seeing this failure to see if it works?

**Comment by NoamTD** [comment]
@NCarlsonMSFT Thank you, it's working now! When can we expect the official release of 17.6?

**Comment by KalyanChanumolu** [comment]
@NCarlsonMSFT The project you uploaded didnt work for me 

Fails with the below error

Exception thrown: 'Azure.Identity.CredentialUnavailableException' in System.Private.CoreLib.dll
Exception thrown: 'Azure.Identity.CredentialUnavailableException' in System.Private.CoreLib.dll
Exception thrown: 'Azure.Identity.CredentialUnavailableException' in System.Private.CoreLib.dll
Exception thrown: 'Azure.Identity.CredentialUnavailableException' in Azure.Identity.dll
Exception thrown: 'Azure.Identity.CredentialUnavailableException' in System.Private.CoreLib.dll
Exception thrown: 'Azure.Identity.CredentialUnavailableException' in System.Private.CoreLib.dll
Exception thrown: 'Azure.Identity.CredentialUnavailableException' in System.Private.CoreLib.dll

**Comment by NCarlsonMSFT** [comment]
@KalyanChanumolu could you please open an issue there with details from the exceptions?

**Comment by asimmon** [comment]
👋 At GSoft, we use Azure resources in almost every service we develop, and we access them with Azure credentials (`DefaultAzureCredential`):

* In cloud environments, we use managed identities (`ManagedIdentityCredential`).
* In local development/testing environments, such as IDEs or command-line tools (`dotnet run`), we use developer credentials issued by `az login` (`AzureCliCredential`).

Since we have several containerized services as dependencies, we tried running them locally using Docker compose. However, the developer credentials authentication failed because the Azure CLI was not included in the services' Docker images. Modifying the Docker images to include Azure CLI was not an option, as we wanted to use our production-ready Docker images.

After reading this GitHub issue thread, we created a local Docker sidecar/companion/proxy to allow developers to use service Docker images with their developer credentials (`az login`) without installing the Azure CLI on those images:

https://github.com/gsoft-inc/azure-cli-credentials-proxy

It is quite similar to this [this solution](https://github.com/Azure/azure-sdk-for-net/issues/19167#issuecomment-1127081646), but it is actually simpler and distributed as a Docker image, making it very easy to consume.

![image](https://user-images.githubusercontent.com/14242083/231509083-4c358775-7c94-4284-bd40-6358fc916c64.png)

**Comment by et1975** [comment]
@asimmon Doesn't solve cross-plat issues, but very elegant solution for linux-on-linux, thank you!

**Comment by asimmon** [comment]
@et1975 Thanks! Could you be more specific about "cross-plat issues"? Because we actually use it on Windows, like:
* I'm on **Windows** and I want to run one of my Linux-based ASP.NET Docker containers that requires Azure credentials with Docker Desktop
* I run `az login` on **WSL** to retrieve unencrypted azure developer credentials in WSL distro's `~/.azure` dir
* I run a new container of our `gsoft-inc/azure-cli-credentials-proxy` proxy using this mount:

```
version: "3"

services:
  azclicredsproxy:
    image: ghcr.io/gsoft-inc/azure-cli-credentials-proxy:latest
    volumes:
      - "\\\\wsl$\\<DISTRONAME>\\home\\<USERNAME>\\.azure\\:/app/.azure/"
```

When I develop on Linux only, I use another mount: `/home/<USERNAME>/.azure:/app/.azure/`

**Comment by et1975** [comment]
@asimmon it's mentioned in the comments here, but essentially cli token is encoded differently on windows (not WSL!).

**Comment by asimmon** [comment]
Yep I understand, the workaround is to install Azure CLI on WSL and use `az login` on WSL. This will give you the same cli token (your developer identity) than on Windows, **but unencrypted**. Then from Windows you can access this unencrypted cli token with this mount: `\\\\wsl$\\<DISTRONAME>\\home\\<USERNAME>\\.azure\\:/app/.azure/`

**Comment by saravanakumarvelayutham** [comment]
@asimmon our work around was to have a pre-build powershell to login by disabling the encryption on windows az cli using experimental flag -> "az config set core.encrypt_token_cache=false;"

**Comment by BC89** [comment]
Greetings,

Not sure if there was a regression but this was working fine after upgrading to 1.9.0+ beta and 17.6 p   but just today I pulled down 17.7.0 p1 and 1.9.0 Azure.Identity and now the following: 

- Visual Studio Token provider can't be accessed at .IdentityService/AzureServiceAuth/tokenprovider.json
 ---> System.AggregateException: Multiple exceptions were encountered while attempting to authenticate. (ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
Status: 400 (Bad Request)

Content:
{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://.vault.azure.net/ was not found in the tenant named kcidev. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: ...

I'm using Azure Batch to run a container and mount a storage share etc. This was working perfectly fine until the upgrade and now the container no longer starts as expected and throws the error above indicating the associated identity is wrong. 

Thanks! 
-BC

**Comment by BC89** [comment]
Sure thing. The account looks correct and I've scrubbed accounts, cleared cache and done an az login.  It's not only happening in my local development env. but also in the deployed version on Azure container app services.



________________________________
From: Nathan Carlson ***@***.***>
Sent: Wednesday, May 17, 2023 2:09 PM
To: Azure/azure-sdk-for-net ***@***.***>
Cc: Brendan Carroll ***@***.***>; Mention ***@***.***>
Subject: [External Email] Re: [Azure/azure-sdk-for-net] [FEATURE REQ] DefaultAzureCredential for local docker testing (#19167)


<https://github.com/BC89>

***From ***@***.*** 410-316-7820 *** This is an External Email from outside of KCI.***
<https://github.com/BC89>
________________________________
@BC89<https://github.com/BC89> for issues specific to the VS Container Tools implementation could you please open an issue at https://github.com/microsoft/DockerTools<https://github.com/microsoft/DockerTools>

For this specific issue, the first thing to check would be the identity used for Azure Service Authentication in VS:
[image]<https://user-images.githubusercontent.com/14239288/239040601-37bcbfc1-9c9b-4a3f-ac3c-fd03a23449e3.png>

**Comment by BC89** [comment]
Created -[Here](https://github.com/microsoft/DockerTools/issues/382) and also had a tread in Azure Batch

**Comment by vitor-baptista-vfx** [comment]
is there any plan for an official solution for people relying on AzureCliCredential?

**Comment by asimmon** [comment]
@vitor-baptista-vfx I agree with @tpanum. Check out our non-intrusive solution which uses a "sidecar-ish" approach to keep supporting `AzureCliCredential` without modifying our existing Docker images: https://github.com/Azure/azure-sdk-for-net/issues/19167#issuecomment-1505493978

**Comment by vmcbaptista** [comment]
@asimmon is your organisation publishing that image publicly? I'm not being able to pull it, I keep getting "Error response from daemon: denied", even though I have done docker login into ghcr.io

**Comment by dferri** [comment]
@tpanum 

> The least destructive hack I have come up with is simply to retrieve secrets (e.g. access token) from my host machine (using Azure CLI) and pass it into my docker container using environment variables, and overrule the azure-identity clients

This seems a good workaround, but how do you use that token?

**Comment by vitor-baptista-vfx** [comment]
For anyone using Jetbrains Rider, there's an issue currently gathering votes to add support for this:
https://youtrack.jetbrains.com/issue/RIDER-94485

**Comment by gamontal** [comment]
> Yep I understand. The workaround is to install Azure CLI on WSL and use `az login` on WSL. This will give you the same cli token (your developer identity) than on Windows, **but unencrypted**. Then **from Windows** you can access this unencrypted cli token with this mount: `\\\\wsl$\\<DISTRONAME>\\home\\<USERNAME>\\.azure\\:/app/.azure/` (path escaped for Docker compose). Use this mount with our proxy and you now have `DefaultAzureCredential `working for Docker on Window-to-Linux.

@asimmon @et1975 Workaround using Docker:
```docker run -it --rm -v "$($HOME)/.azure-docker:/root/.azure" mcr.microsoft.com/azure-cli az login```

docker-compose volume config: ```<path>/.azure-docker:/app/.azure"```

**Comment by jaredpar** [comment]
Now that the Azure token cache is [encrypted by default](https://learn.microsoft.com/en-us/cli/azure/msal-based-azure-cli) the traditional approach of volume mapping `${USERPROFILE}\.azure:/root/.azure` no longer works. This thread seems to have settled on two approaches to working around that. 

1. Use `az config set core.encrypt_token_cache=false`. This effectively undoes the encryption and restores the ability to directly volume map from Windows to Docker. 
2. Use `az login` in WSL then volume map from WSL to docker `\\\\wsl$\\<DISTRONAME>\\home\\<USERNAME>\\.azure\\:/app/.azure`

I'm trying to understand the downsides of (1) compared to (2). The setup for (1) is much easier: a one time command. Yes it leaves the tokens un-encrpyted on the hard drive but so does (2) as Linux does not encrypt the tokens (to my understanding at least). (2) is a bit more awkward to steup and requires that you keep WSL logins active which is another item to maintain. 

Is there something I'm missing in my analysis here that would make me want to prefer (2)?

**Comment by vthokie93** [comment]
Sorry if this is slightly off topic, but is this solution quoted below only meant to work when running in debug mode or should it also work when using a docker run command in PowerShell?

>Now that the Azure token cache is [encrypted by default](https://learn.microsoft.com/en-us/cli/azure/msal-based-azure-cli) the traditional approach of volume mapping ${USERPROFILE}\.azure:/root/.azure no longer works. This thread seems to have settled on two approaches to working around that.
> 1. Use `az config set core.encrypt_token_cache=false`. This effectively undoes the encryption and restores the ability to directly volume map from Windows to Docker.

**Comment by krukowskid** [comment]
A summary for everyone with a standard use case. In order to use your Visual Studio identity in a local docker container when debugging in VS you will need the following: 
- Visual Studio 17.6 or later.
- `azure.identity` package version 1.9.0 or later.
- `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` package version 1.18.1 or later.
- Docker Desktop with WSL (for Windows machines).
- A Dockerfile for your project.

If you use `DefaultAzureCredential()` will seamlessly work when running the container from VS, as it maps a volume with VS identity token to the container. For more detailed information, [refer to my blog post](https://cloudchronicles.blog/blog/Azure-Managed-Identity-with-Local-Docker-Containers-in-Visual-Studio/) for detailed info.

**Comment by jaredpar** [comment]
@krukowskid read through your post and still having trouble understanding how this is working. The current problem started happening because the Azure CLI is encrypting the tokens on disk. This means previous solutions that mapped Windows drives to Linux fail because Linux OS isn't able to decrypt the tokens. 

The blog post indicates that the solution is using drive mapping to solve the problem. For that to work, based on what I've learned thus far, the token must be un-encrypted. Or the targets / tasks are doing some magic in the middle to decrypt the token before volume mounting occurs. Can you elaborate on the mechanism at work here? Particularly if it's something else I'm not considering 😄

**Comment by krukowskid** [comment]
Hey @jaredpar, this is a built-in mechanism introduced in the latest updates that doesn't use Azure CLI but relies on Visual Studio's logged-in identity. The mapping is handled by Visual Studio itself, so all you need are the correct versions of packages. However, it's worth noting that this mechanism works with the mcr.microsoft.com/dotnet/sdk:6.0 image but won't work with the alpine image :(

@NCarlsonMSFT, could you share with us how this works underneath and what's required to use it with the alpine image?

**Comment by NCarlsonMSFT** [comment]
@jaredpar the volume mount is not for tokens, it is for a Proxy that VS uses to handle Token Requests: https://learn.microsoft.com/en-us/visualstudio/containers/container-tools-configure?view=vs-2022#configure-azure-authentication

**Comment by NCarlsonMSFT** [comment]
@krukowskid Can you try with the latest preview: https://visualstudio.microsoft.com/vs/preview/ I believe the Alpine issue has been fixed there.

**Comment by krukowskid** [comment]
@NCarlsonMSFT installed preview version `17.7.0 Preview 5.0` and problem still persist.

**Comment by NCarlsonMSFT** [comment]
@krukowskid could you open an issue over at https://github.com/microsoft/DockerTools with a link to a repro project? I just did a quick test retargeting my sample (https://github.com/NCarlsonMSFT/VisualStudioCredentialExample) to mcr.microsoft.com/dotnet/runtime:6.0-alpine and was able to get a token.

**Comment by krukowskid** [comment]
@NCarlsonMSFT  I've missed that after installing preview version, VS asked me to "Re-enter my credentials". I can confirm its working with preview version. Can't wait for the stable release!

**Comment by henriksen** [comment]
Any immediate plans of making the VS proxy work with AzureCliCredential outside of VS? So I don't have to run the container(s) though Visual Studio?

**Comment by kjreuter** [comment]
@krukowskid @NCarlsonMSFT Does this only work with WSL? Will it work with the mcr.microsoft.com/dotnet/aspnet:6.0 image?

I followed @krukowskid's blog post's instructions using Docker Desktop (minus WSL) with mcr.microsoft.com/dotnet/aspnet:6.0 and the latest versions of the required packages and Visual Studio, but am getting a 403 on a ManagedIdentityCredential requests to 169.254.169.254. I understand that IMDS uses that IP in Azure, but it is not routable and should not be being used locally, and based on the blog post, I would expect that VisualStudioIdentity should be used locally. 

One other item potentially of note, if I run Fiddler, the request succeeds.

**Comment by christothes** [comment]
@kjreuter This 403 response from Docker is a [known issue ](https://github.com/Azure/azure-sdk-for-net/issues/38218#issuecomment-1683085316)- we should have a fix soon for it.

**Comment by kjreuter** [comment]
@christothes Your workaround and downgrading to version 1.9.0 of Azure.Identity both worked. Thank you! I will keep an eye out for a new version with a fix...

**Comment by jonnekleijer** [comment]
Some teammates are on mac's and since [VS will be retired next year for mac](https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/), it would be great to see the VS proxy feature land in VSCode as well.

**Comment by svrooij** [comment]
Drumroll 🥁 ..... I've managed to use `DefaultAzureCredentials` in docker with the use of an **open-source** proxy (build by myself). https://svrooij.io/2023/08/03/emulate-managed-identities/

I know this is not a real solution but at least you can start testing your apps running in docker.

**Comment by flaxh** [comment]
I tried solution proposed by @krukowskid via example from https://github.com/NCarlsonMSFT/VisualStudioCredentialExample.
I successfully authenticate but only in isolated Azure function app. Do you have any idea why I'm getting "Visual Studio Token provider can't be accessed at /home/.IdentityService/AzureServiceAuth/tokenprovider.json" for in-process function app ?

**Comment by NCarlsonMSFT** [comment]
@flaxh the error message is that the VisualStudioCredential isn't configured properly. The underlying issue is that the Integrated Azure Functions images don’t have a dotnet runtime so the proxy isn’t able to run. I’ve updated the sample with a new project [FunctionAppIntegrated](https://github.com/NCarlsonMSFT/VisualStudioCredentialExample/tree/master/FunctionAppIntegrated) that demonstrates a work-around to unblock debugging.

**Comment by rhythmnewt** [comment]
@NCarlsonMSFT I tried your visual studio credential and it worked properly for me with the isolated function project, I was able to run the function both locally and in docker using your solution. However, I hit a snag when trying this approach in my solution.

In my solution I have a service bus queue trigger that authenticates using managedidentity (configured in the local.settings.json)
``` "MyServiceBusConnection__fullyQualifiedNamespace": "[myservicebus].servicebus.windows.net"```

In this case when debugging or running the project within docker, the authentication to servicebus fails with this exception in console (it works with VisualStudioCredential when executing natively in VS2022). It just can't authenticate the listener, even though it should be using same VisualStudioCredential under the hood.

```
Azure.Identity: ManagedIdentityCredential authentication failed: Managed Identity response was not in the expected format. See the inner exception for details.
```

I was able to create a basic replication using your solution.
In the FunctionAppIsolated project add nuget package:
```    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.14.0" />```
Add new function definition in Function1.cs
```
        [Function("ProcessMessage")]
        public async Task ProcessMessageAsync([ServiceBusTrigger("%QueueName%", Connection = "ServiceBusConnection")] ServiceBusReceivedMessage receivedMessage, CancellationToken cancellationToken, ServiceBusMessageActions messageActions, FunctionContext context)
        {

            IDictionary<string, string> messageProperties = new Dictionary<string, string>();

            var message = receivedMessage.Body.ToString();
            Console.WriteLine(message);
        }
```
update local.settings.json
```
   "QueueName": "[your sample queue]",
   "ServiceBusConnection__fullyQualifiedNamespace": "[sample service bus instance].servicebus.windows.net"
```

**Comment by NCarlsonMSFT** [comment]
@rhythmnewt If you're only getting an error from ManagedIdentityCredential then the other identity providers aren't being used. I've found some docs on how this is supposed to work locally: [Guidance for developing Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=servicebus&pivots=programming-language-csharp#local-development-with-identity-based-connections). If those docs don't help, you're best bet is to contact the Azure Functions team : [Azure Functions questions](https://github.com/Azure/Azure-Functions#questions--help)

**Comment by verydarkmagic** [comment]
Hmm, closed by bot after 3 years :D 
I think this issue is a really accurate picture of development for Azure as a whole.
Rich on marketing promises, confusing on pricing, and downright abysmal on actual features.

**Comment by jsheetzmt** [comment]
@NCarlsonMSFT Are you aware of any issues with TokenService.Proxy not appearing when using 17.10.0 Preview 5.0? The TokenService.Proxy bind mount isn't appearing when using latest preview version of VS. Works fine with 17.9

**Comment by NCarlsonMSFT** [comment]
@jsheetzmt in 17.10 the various helper CLIs for supporting the container tools got moved into one mount `/VSTools`. Does that appear? Are you having an issue with getting Tokens in 17.10? If so, please open an issue in [microsoft/DockerTools](https://github.com/microsoft/DockerTools).

**Comment by svrooij** [comment]
I never saw this working, so I checked my settings and it's turned on, I never turned it on, so I guess its on by default. Does not work, never did.

Windows 10
Visual Studio Enterprise 2022 17.9

Back to using my open-source implementation.... https://svrooij.io/2023/08/03/emulate-managed-identities/
Which just works everywhere, without any complicated mounts, just setting a single environment variable and poof it works.

**Comment by jongio** [comment]
Reopening as we still need to figure this out
