### ISSUE TITLE
[BUG] Instantiating ServiceBusClient results in NotImplementedException

### ISSUE THREAD

**Issue by bizmonger** [Azure/azure-sdk-for-net#24446]
Maybe related to this [bug][1].

**I receive a *NotImplementedException* for the following line:**

    serviceBusClient <- new ServiceBusClient(connectionString) // NotImplementedException

**The context is as follows:**

    open Azure.Messaging.ServiceBus
    ...
    let mutable serviceBusClient : ServiceBusClient = null
    ...
    serviceBusClient <- new ServiceBusClient(connectionString) // NotImplementedException

**IAsyncDisposable:**

I received the same exception when removing the "new" declaration since the class no longer implemented *IDisposable*, but rather *IAsyncDisposable*:

    serviceBusClient <- ServiceBusClient(connectionString) // NotImplementedException

[![enter image description here][2]][2]

**Additional Information:**

* I was unable to reproduce this anomaly in a separate integration test (NUnit)

* I only observe this anomaly when running a Xamarin.Forms app using the Android emulator

* The same code was working two months ago

* Originally observed exception using Azure.Messaging.ServiceBus version 7.3.0 (Nuget)

* Also observed exception using Azure.Messaging.ServiceBus version 7.1.2 (Nuget)

* Using .NetStandard 2.1

* I increased output verbosity to *Diagnostics* without observing any additional clues

* Azure.Messaging.ServiceBus (version 7.0 works)

**QuickWatch:**

[![enter image description here][3]][3]

**Call Stack:**
[![enter image description here][4]][4]

  [1]: https://github.com/Azure/azure-sdk-for-net/issues/24055
  [2]: https://i.stack.imgur.com/5Jhst.png
  [3]: https://i.stack.imgur.com/y6gjt.png
  [4]: https://i.stack.imgur.com/Hhbcm.png
**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Hi @bizmonger.  Thank you for reaching out and we regret that you're experiencing difficulties.  As you mentioned, this was a known issue that was recently patched.  This should be fixed with [v7.4.0](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.4.0) of the `Azure.Messaging.ServiceBus` package that was released earlier today.

Would you be so kind as to try updating to v7.4.0 and let us know if you're still seeing the issue?

**Comment by bizmonger** [comment]
@jsquire The issue appears to be resolved.

I still get a not implemented exception the very first time I hit that line.
However, I'm able to execute the code anyway without issues.

Thanks.
