### ISSUE TITLE
[Translation] DocumentTranslationWithGlossary failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#28896]
Translation nightly test runs are failing with:

> Error message
> Expected: some item equal to "glossaryFirst"
> But was:  < "Primer", "documento", "de", "glossaryTest", "en", "inglés
> " >
> 
> 
> Stack trace
>    at Azure.AI.Translation.Document.Tests.TranslationOperationLiveTests.DocumentTranslationWithGlossary() in /Users/runner/work/1/s/sdk/translation/Azure.AI.Translation.Document/tests/TranslationOperationLiveTests.cs:line 450
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1587726&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
//fyi:  @maririos

**Comment by maririos** [comment]
I looked into it and something changed from the service side. I have pinged them on the Teams Channel with the details of my investigation

**Comment by maririos** [comment]
Service confirmed it was a regression. The fix has been merged and is currently on deployment. Hopefully we will start seeing it by next week

**Comment by maririos** [comment]
Fixed. see latest run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1619025&view=results

**Comment by JoshLove-msft** [comment]
This failed a bunch of times today (6/8) - [DocumentTranslationWithGlossary](https://dev.azure.com/azure-sdk/public/_test/analytics?definitionId=297&contextType=build)

**Comment by JoshLove-msft** [comment]
I see this issue was initially written about the live test, but Playback is still failing regularly.
