### ISSUE TITLE
Latest Version (1.1.2) restricts to Newtonsoft.Json < 7.0.0

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/azure-sdk-for-net#3002]
Hyak.Common should be working with Newtonsoft.Json 10.0.1 by now and was compatible with version 9 in 1.1.1 but now the new 1.1.2 is even worse and restricted to < 7.

Please fix this so that it's marked as compatible with 10. (it shouldn't have any restriction at all because there are no breaking changes in newtonsoft.json)

**Comment by markcowl** [comment]
@JohnGalt1717 There actually are breaking changes, later versions of Newtonsoft.Json remove the json schema validation functionality that was available in 6.x.

The .NetCore versions depend on Newtonsoft.json 9, the net45 versions do not yet, though we will likely update this for all the runtimes in a near term sprint.

**Comment by JohnGalt1717** [comment]
The issue is that we're now blocked from getting the latest version of both your package and newtonsoft.json which the longer you wait to fix this the more things that depend on the new functionality in newtonsoft.json are going to be out of our reach.  Given that you went backwards and no longer even support 8 and  9.x which everyone has been on for over a year this should be an incredibly high priority to fix this and get it done right before you start causing versioning issues.

**Comment by cleverguy25** [comment]
This is the same as https://github.com/Azure/azure-sdk-for-net/issues/2871

**Comment by geekcubed** [comment]
Chip in my 2 cents here:

The JsonSchema functionality was marked as obsolete as of version 7 - almost two years ago.  That has given you ample time to prepare for it's removal (which has finally occurred as of v10).  

You've version locked to 6 and 7 in order to provide a band-aid approach to the issue - this is a seriously smelly fix.  Your decision has in turn has made you package a problem for the rest of us - we're either stuck using an older version of the package, or forced to use an older version of Json.Net - and not only a slightly older version, but one that is two years behind current and missing a massive slew of bug fixes (not to mention features).

**Comment by davecader** [comment]
Rolling back to a version of Json.net that is years old is not a viable solution. Microsoft, you need to come up with better solution.

**Comment by minghan** [comment]
@markcowl This issue is causing a lot of pain for internal Microsoft teams too.

**Comment by konste** [comment]
Our product uses more than 200 external NuGet packages and limiting JSON.net to <7 causes quite a disruption, as we don't have a version to satisfy all packages now! Before it was 9.1

Please do something ASAP!

**Comment by markcowl** [comment]
@JohnGalt1717 @davecader @minghan @konste @geekcubed @cleverguy25 I'd be curious to know what library you are using that requires Hyak.Common, as almost all ARM libraries use Microsoft.Rest.ClientRuntime.  It would be simple enough to simply remove the upper limit on the dependency, since we know that no existing version of Newtonsoft.Json causes issues with the generated code.

**Comment by GeekActual** [comment]
@markcowl Here is just ONE Of the dependency trails I have for Hyak.Common 

I need to use the CertificateCloudCredentials and ComputeManagementClient classes that are in the Microsoft.WindowsAzure.Management.Computer library

Microsoft.WindowsAzure.Management.Computer.14.0.0 depends on 
Microsoft.Azure.Common 2.0.4 (or better) [I'm using 2.1] which depends on
Hyak.Common 1.0.2 (or better) [I'm using  v1.1.2]

Which rules out Json.net greater than or equal to 7

**Comment by markcowl** [comment]
@GeekActual Why are you using Microsoft.WindowsAzure.Management.Compute, instead of Microsoft.Azure.Management.Compute?  Just curious, this is a very old RDFE library.

This should now be fixed with Hyak.Common 1.1.3

**Comment by konste** [comment]
Finally! Thank you!

**Comment by JohnGalt1717** [comment]
This is not fixed. Hyak.common 1.1.3 requires < 10.0.0 

Microsoft.azure.common requires hyak.common.

Anything that requires Microsoft.azure.common uses this chain.

Please reopen and actually fix the problem and make those work with newtonsoft.json 10
