### ISSUE TITLE
AzureServiceTokenProviderException not marked Serializable

### ISSUE THREAD

**Issue by leniency** [Azure/azure-sdk-for-net#4370]
I get an error when doing a full publish build of an ASP.Net MVC 5 application. It occurs during the step that compiles and merges views (aspnet_compiler.exe)

`Error ASPRUNTIME: Type 'Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException' in assembly 'Microsoft.Azure.Services.AppAuthentication, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.`

Checking the code, it looks like `Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException` indeed is not marked as serializable.  Other exception classes in other libraries have this clause at the top:

```
#if FullNetFx
    [Serializable]
#endif
```
(ie, Microsoft.Rest.HttpOperationException)

Is this an oversight on the AzureServiceTokenProviderException class, or should I look elsewhere?

**Comment by varunsh-msft** [comment]
We are working on a fix. Should be out in a week at most.

**Comment by nonik0** [comment]
@leniency We have just published version 1.0.3 of AppAuthentication to NuGet, which includes the fix to mark AzureServiceTokenProviderException as serializable. Thanks for your input!

**Comment by varunsh-msft** [comment]
@leniency , can you please close this issue? Thanks!

**Comment by adfew** [comment]
It is serializable now but it still not working. Now exception message looks like that:

> System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException' was not found. 

Try to unit test this functionality after fix it :)

**Comment by dgliwa** [comment]
@varunsh-msft and @nonik0, not sure if this is related, but i'm trying to publish an app with this package, and I'm getting the following error:

> Type is not resolved for member 'Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException,Microsoft.Azure.Services.AppAuthentication, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by dgliwa** [comment]
I should note that I only get that error when trying to publish and my web.config is set up to use managed identity (`connectionString="RunAs=App"`)

**Comment by dgliwa** [comment]
Never mind - it has to do with us precompiling as part of the publish.  Sorry for the notifications!

**Comment by joelwetzel** [comment]
@dgliwa could you provide more info on your fix?  Since adding keyvault support to our application, we're seeing the same "Type is not resolved for member AzureServiceTokenProviderException" when building in an AzureDevops pipeline.

Our MSBuild parameters are:
/p:DeployOnBuild=True /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PublishProfile=$(DeploymentConfiguration) /p:TransformConfigFile=true /p:AutoParameterizationWebConfigConnectionStrings=False

**Comment by dgliwa** [comment]
@joelwetzel in our publishing profile we had the parameter `PrecompileBeforePublish` set to true.  By setting it to false the error went away.

**Comment by joelwetzel** [comment]
@dgliwa Thanks!  Yes, it looks like we have that in our publishing profile too.  Disabling it made the error go away.  This seems like a bug in this nuget package, if it can't be precompiled.

**Comment by dgliwa** [comment]
@joelwetzel Yeah seems like a bit of a chicken/egg situation, where to precompile it may need to load some secrets, but the secrets can't be loaded with the connection string provided in your config until the code is running on the instance you've granted access to.

**Comment by joelwetzel** [comment]
I'm not sure it has to do with the secrets.  The secrets aren't accessed until runtime, I believe.  To me it looked like the dll isn't labelling that type correctly.  But it's over my head, so I'll sit back and hope someone is watching these comments.

**Comment by dil-bpecor** [comment]
Any update seeing the same issue with  /p:PrecompileBeforePublish=true 

Error:
##[error]ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type 'Azure.Identity.CredentialUnavailableException' in assembly 'Azure.Identity, Version=1.1.1.0, Culture=neutral, PublicKeyToken=XXX' is not marked as serializable.

Build parameters:
 msbuildArgs: '/p:SolutionDir="$(System.DefaultWorkingDirectory)" /p:DeployOnBuild=true /p:PrecompileBeforePublish=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

Works fine without (/p:PrecompileBeforePublish=true)
 msbuildArgs: '/p:SolutionDir="$(System.DefaultWorkingDirectory)" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

**Comment by rushilShetty** [comment]
@dgliwa @dil-bpecor 
I'm having the same issue now
> ##[error]ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type is not resolved for member 'Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException,Microsoft.Azure.Services.AppAuthentication, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

I have a aspnet project which builds fine locally, but on Azure DevOps I get this same exact error. We use our own build agent. I installed Visual studio on it and built and that's fine. But when I use it with MSbuild.exe, I get the above error.

I don't have /p:PrecompileBeforePublish parameter any where in our project. Even then I provided it /p:PrecompileBeforePublish=false, but it still doesn't seem to work. Would you know perhaps any other reason?
