### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by ujimenez71** [Azure/azure-sdk-for-net#47696]
### Library name and version

 Azure.ResourceManager.AppService 1.3.0

### Query/Question

Hi,

When I try to update/redeploy a workflow definition using the DeployWorkflowAsync method I get the following error:

Error deploying workflow artifacts. Please see 'details' for each failure.
Status: 400 (Bad Request)
ErrorCode: BadRequest

Content:
{"error":{"details":[{"target":"wf-int-UjrTests-dev-weu-01","code":"PreconditionFailed","message":"Error deploying workflow artifact: 'wf-int-UjrTests-dev-weu-01' Etag mismatch"}],"code":"BadRequest","message":"Error deploying workflow artifacts. Please see 'details' for each failure."}}

For non existent workflows the method works well and the worklow is created.

It is possible to update a workflow using the SDK?

Thanks
![Image](https://github.com/user-attachments/assets/d0f46278-1732-4dd4-9070-c9981e932309)

### Environment

Windows 10 .NET 8.0
Visual Studio Professional 17.12.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by DevArjun23** [comment]
Can you add "If-Match" header with value "*" to your request?

**Comment by DevArjun23** [comment]
I have logged a bug for this behavior and the fix is planned to be implemented up later this month.
Here's bug id for your reference: 31314070

**Comment by ujimenez71** [comment]
> Can you add "If-Match" header with value "*" to your request?

Hi, @DevArjun23 I looked how to add the header to the request, but I could not find a way to do it. Thanks for the support.

**Comment by welovej** [comment]
This problmes was caused by service end. And They said that It’ll be fixed in existing version later this month. 
Stay tuned.

**Comment by ujimenez71** [comment]
Hi,

Can you give an update? It is still not working.

Thanks and kind regards

**Comment by welovej** [comment]
@DevArjun23  how's it going? Did we have some update?

**Comment by ujimenez71** [comment]
Good day,

Any news?

Thanks

**Comment by welovej** [comment]
> Good day,
> 
> Any news?
> 
> Thanks

Service team is dealing with PR. I suppose it won't be too long to come out.
